---
apiVersion: v1
kind: pod
metadata: 
  name: spec
  labels:
    env: Dev
    app: spc
spec:
  containers:
    - name: spc app
      image: shaikkhajaibrahim/spcjan2024:1.0
      resources:
        requests:
          cpu: 250m
          memory: 64M
        limits:
          cpu: 500m
          memory: 256M
      ports:
        - containerPort: 8080
          protocol: TCP